"""Bindings to the Rust durable kernel. Records are pi-durable's JSON dicts."""

from collections.abc import AsyncIterator, Awaitable
from typing import Any, Literal, TypeAlias

Json: TypeAlias = Any
Record: TypeAlias = dict[str, Any]
Scope: TypeAlias = dict[str, Any]
Frame: TypeAlias = dict[str, Any]

class DurableError(Exception): ...
class InvalidWrite(DurableError): ...
class ReadAfterWrite(DurableError): ...
class TransactionFinished(DurableError): ...
class SessionClosed(DurableError): ...
class SessionLocked(DurableError): ...
class CorruptStorage(DurableError): ...
class InvocationEnded(DurableError): ...
class FramesLagged(DurableError): ...

class Frames(AsyncIterator[Frame]):
    def __aiter__(self) -> Frames: ...
    def __anext__(self) -> Awaitable[Frame]: ...

class Session:
    @staticmethod
    def open(path: str | None = None) -> Awaitable[Session]: ...
    def close(self) -> Awaitable[None]: ...
    def begin(self) -> Tx: ...
    def subscribe(self) -> Frames: ...
    def reserve(self, kinds: list[str]) -> Awaitable[tuple[Record, Literal["run", "abort"]] | None]: ...
    def seq(self) -> Awaitable[int]: ...
    def conversation(self, id: int) -> Awaitable[Record | None]: ...
    def conversations(self, after: int | None = None, limit: int = 1000) -> Awaitable[list[Record]]: ...
    def owned_conversations(self, task: int) -> Awaitable[list[Record]]: ...
    def entry(self, id: int) -> Awaitable[Record | None]: ...
    def entries(self, conversation: int, after: int | None = None, limit: int = ...) -> Awaitable[list[Record]]: ...
    def context(self, conversation: int, at: int | None = None) -> Awaitable[list[Record]]: ...
    def task(self, id: int) -> Awaitable[Record | None]: ...
    def tasks(
        self,
        *,
        conversation: int | None = None,
        kind: str | None = None,
        status: str | None = None,
        abort_requested: bool | None = None,
        background: bool | None = None,
        live: bool = False,
    ) -> Awaitable[list[Record]]: ...
    def submission(self, id: int) -> Awaitable[Record | None]: ...
    def submission_by_request(self, conversation: int, request_id: str) -> Awaitable[Record | None]: ...
    def submissions(self, conversation: int, status: str | None = None) -> Awaitable[list[Record]]: ...
    def doc(self, kind: str, scope: Scope, key: str | None = None, at: int | None = None) -> Awaitable[Record | None]: ...
    def docs(self, scope: Scope, kind: str | None = None) -> Awaitable[list[Record]]: ...
    def wait_task(self, id: int) -> Awaitable[Record]: ...
    def wait_submission(self, id: int) -> Awaitable[Record]: ...
    def dump(self) -> Awaitable[Json]: ...

class Tx:
    def conversation(self, id: int) -> Awaitable[Record | None]: ...
    def owned_conversations(self, task: int) -> Awaitable[list[Record]]: ...
    def entry(self, id: int) -> Awaitable[Record | None]: ...
    def context(self, conversation: int) -> Awaitable[list[Record]]: ...
    def task(self, id: int) -> Awaitable[Record | None]: ...
    def tasks(
        self,
        *,
        conversation: int | None = None,
        kind: str | None = None,
        status: str | None = None,
        abort_requested: bool | None = None,
        background: bool | None = None,
        live: bool = False,
    ) -> Awaitable[list[Record]]: ...
    def submission(self, id: int) -> Awaitable[Record | None]: ...
    def submission_by_request(self, conversation: int, request_id: str) -> Awaitable[Record | None]: ...
    def submissions(self, conversation: int, status: str | None = None) -> Awaitable[list[Record]]: ...
    def doc(self, kind: str, scope: Scope, key: str | None = None) -> Awaitable[Json | None]: ...
    def create_root(self) -> int: ...
    def create_conversation(self, *, parent: Record | None = None, owner: Record | None = None) -> int: ...
    def append_entry(
        self, conversation: int, kind: str, content: Record | None = None, *, head: int | Literal["self"] | None = None, by_task: int | None = None
    ) -> int: ...
    def create_task(
        self, conversation: int, kind: str, input: Json, checkpoint: Json, *, version: int = 1, owner: int | None = None, background: bool = False
    ) -> int: ...
    def set_task_state(self, id: int, state: Record) -> None: ...
    def release_task(self, id: int) -> None: ...
    def abort_task(self, id: int) -> None: ...
    def create_submission(self, conversation: int, content: Record, *, request_id: str | None = None, status: str = "queued") -> int: ...
    def put_submission(self, record: Record) -> None: ...
    def put_doc(
        self,
        kind: str,
        scope: Scope,
        value: Record,
        *,
        key: str | None = None,
        version: int = 1,
        history: Literal["latest", "rewindable"] | None = None,
        fork: Literal["current", "initial", "asOf"] | None = None,
    ) -> None: ...
    def retire_doc(self, kind: str, scope: Scope, key: str | None = None) -> None: ...
    def commit(self) -> Awaitable[Frame]: ...
    def rollback(self) -> None: ...

class Scheduler:
    def __init__(self, session: Session) -> None: ...
    def register(self, kind: str, handler: object) -> None: ...
    def stop(self) -> Awaitable[None]: ...

class Invocation:
    @property
    def task(self) -> Record: ...
    @property
    def mode(self) -> Literal["run", "abort"]: ...
    @property
    def session(self) -> Session: ...
    def step(self) -> Step: ...

class Step:
    @property
    def tx(self) -> Tx: ...
    @property
    def task(self) -> Record: ...
    def advance(self, checkpoint: Json) -> None: ...
    def wait(self, on: list[int], checkpoint: Json, *, policy: Literal["allSettled", "failFast"] = "allSettled") -> None: ...
    def finish(self, result: Json = None) -> None: ...
    def fail(self, message: str, detail: Json = None) -> None: ...
    def aborted(self, reason: str | None = None) -> None: ...
    def commit(self) -> Awaitable[Frame]: ...
    def rollback(self) -> None: ...
