"""`FlowMiddleware`: agent middleware whose hook bodies are written once as flows.

`AgentMiddleware` exposes every hook as a sync/async pair. `deepagents._flow`
lets a hook body be written once as a *flow* (a generator yielding effects),
but each middleware still had to hand-write the two driver methods:

```python
def wrap_model_call(self, request, handler):
    return run_flow(self.model_call_flow(request), handler)


async def awrap_model_call(self, request, handler):
    return await arun_flow(self.model_call_flow(request), handler)
```

`FlowMiddleware` removes that boilerplate. Subclasses define flow methods and
the matching hook pairs are generated onto the subclass automatically:

| Flow method defined on subclass | Hooks generated              |
|---------------------------------|------------------------------|
| `before_agent_flow`             | `before_agent`/`abefore_agent` |
| `before_model_flow`             | `before_model`/`abefore_model` |
| `after_model_flow`              | `after_model`/`aafter_model`   |
| `after_agent_flow`              | `after_agent`/`aafter_agent`   |
| `model_call_flow`               | `wrap_model_call`/`awrap_model_call` |
| `tool_call_flow`                | `wrap_tool_call`/`awrap_tool_call`   |

Hooks are generated onto each subclass's own `__dict__` (and only for flows
that subclass defines), so `create_agent`'s hook-participation checks
(`cls.wrap_model_call is not AgentMiddleware.wrap_model_call`) see exactly
the hooks the middleware really implements. An explicitly defined hook always
wins over a generated one. Node-hook drivers forward `*args` and adopt the
flow method's signature, so flows may take the extended
`(state, runtime, config)` parameter list; a `__can_jump_to__` list set on a
flow method is copied onto its generated hooks.

Example:
    ```python
    class MyMiddleware(FlowMiddleware):
        def model_call_flow(self, request: ModelRequest) -> Flow[ModelResponse]:
            data = yield flows(backend).read(path)
            return (yield Call(request.override(...)))
    ```
"""

from __future__ import annotations

import inspect
from typing import TYPE_CHECKING, Any, cast

from langchain.agents.middleware.types import AgentMiddleware, ContextT, ResponseT, StateT

from deepagents._flow import arun_flow, run_flow

if TYPE_CHECKING:
    from collections.abc import Callable

_NODE_FLOWS: dict[str, tuple[str, str]] = {
    "before_agent_flow": ("before_agent", "abefore_agent"),
    "before_model_flow": ("before_model", "abefore_model"),
    "after_model_flow": ("after_model", "aafter_model"),
    "after_agent_flow": ("after_agent", "aafter_agent"),
}

_WRAP_FLOWS: dict[str, tuple[str, str]] = {
    "model_call_flow": ("wrap_model_call", "awrap_model_call"),
    "tool_call_flow": ("wrap_tool_call", "awrap_tool_call"),
}


def _finalize_hook(hook: Callable[..., Any], cls: type, hook_name: str, flow_name: str, flow_fn: Callable[..., Any] | None) -> Callable[..., Any]:
    """Attach metadata so the generated hook behaves like a hand-written one.

    For node hooks (`flow_fn` given), the flow method's signature is adopted
    so callers that inspect hook signatures (e.g. config injection) see the
    flow's true parameter list, and `__can_jump_to__` is copied for the
    factory's jump-target detection. Wrap hooks keep their natural
    `(request, handler)` signature.
    """
    fn = cast("Any", hook)
    fn.__name__ = hook_name
    fn.__qualname__ = f"{cls.__qualname__}.{hook_name}"
    fn.__doc__ = f"Generated by `FlowMiddleware`: drives `{flow_name}` (see `deepagents._flow`)."
    if flow_fn is not None:
        fn.__signature__ = inspect.signature(flow_fn)
        if hasattr(flow_fn, "__can_jump_to__"):
            fn.__can_jump_to__ = cast("Any", flow_fn).__can_jump_to__
    return hook


def _node_hooks(flow_name: str) -> tuple[Callable[..., Any], Callable[..., Any]]:
    """Build the sync/async hook pair driving a handler-less (node) flow."""

    def sync_hook(self: FlowMiddleware, *args: Any, **kwargs: Any) -> Any:  # noqa: ANN401
        return run_flow(getattr(self, flow_name)(*args, **kwargs))

    async def async_hook(self: FlowMiddleware, *args: Any, **kwargs: Any) -> Any:  # noqa: ANN401
        return await arun_flow(getattr(self, flow_name)(*args, **kwargs))

    return sync_hook, async_hook


def _wrap_hooks(flow_name: str) -> tuple[Callable[..., Any], Callable[..., Any]]:
    """Build the sync/async hook pair driving a handler-based (wrap) flow."""

    def sync_hook(self: FlowMiddleware, request: Any, handler: Callable[[Any], Any]) -> Any:  # noqa: ANN401
        return run_flow(getattr(self, flow_name)(request), handler)

    async def async_hook(self: FlowMiddleware, request: Any, handler: Callable[[Any], Any]) -> Any:  # noqa: ANN401
        return await arun_flow(getattr(self, flow_name)(request), handler)

    return sync_hook, async_hook


class FlowMiddleware(AgentMiddleware[StateT, ContextT, ResponseT]):
    """Middleware base class that generates hook pairs from flow methods.

    See the module docstring for the flow-method-to-hook mapping and an
    example. Subclasses define flow methods only; the sync and async hook
    variants are generated.
    """

    def __init_subclass__(cls, **kwargs: Any) -> None:
        """Generate hook pairs for every flow method defined on `cls`."""
        super().__init_subclass__(**kwargs)
        for flow_name, (sync_name, async_name) in (*_NODE_FLOWS.items(), *_WRAP_FLOWS.items()):
            flow_fn = cls.__dict__.get(flow_name)
            if flow_fn is None:
                continue
            is_wrap = flow_name in _WRAP_FLOWS
            sync_hook, async_hook = (_wrap_hooks if is_wrap else _node_hooks)(flow_name)
            node_flow_fn = None if is_wrap else flow_fn
            if sync_name not in cls.__dict__:
                setattr(cls, sync_name, _finalize_hook(sync_hook, cls, sync_name, flow_name, node_flow_fn))
            if async_name not in cls.__dict__:
                setattr(cls, async_name, _finalize_hook(async_hook, cls, async_name, flow_name, node_flow_fn))


__all__ = ["FlowMiddleware"]
